apiVersion: v1
kind: Service
metadata:
  name: tidb-internal
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    cloud.google.com/healthcheck-port: "10088"
    cloud.google.com/backend-config: '{"default": "tidb-backend-config"}'
spec:
  type: LoadBalancer
  selector:
    app: tidb
  ports:
  - port: 4000
    targetPort: 4000
    name: tidb
  - port: 10088
    targetPort: 10088
    name: readiness
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
