apiVersion: v1
kind: Service
metadata:
  name: mysql-internal
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
      #- port: 3306 #10088
      #targetPort: 3306 #10088
      #name: readiness
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
