apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 500
      containers:
      - name: mysql
        image: asia-northeast1-docker.pkg.dev/gcp-jp-tech-team/mysql-graceful-images/mysql:8.0
        imagePullPolicy: Always
          # command: ["/bin/sh", "-c", "sleep 3600"]
        ports:
        - containerPort: 3306
        - containerPort: 10088
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "NNU9bgtBy5wxcE2c"
        #lifecycle:
        #  preStop:
        #    exec:
        #      command:
        #      - sleep
        #      - "360"
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3306 # todo: change to 10088
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: mysql-node
                operator: In
                values:
                - "true"
        podAntiAffinity:  # Pod should not be scheduled on the same node as other Pods with the same label
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: mysql
            topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: "mysql-node"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
      storageClassName: "standard-rwo" # todo: change to your storage class
